### ISSUE TITLE
Support v3io://container/path in dask and friends

### ISSUE THREAD

**Issue by tebeka** [v3io/v3io-fs#3]
We'd like to support `v3io://container/path/to/file` in data, no need to specificy the server (e.g. `V3IO_API`)

**Comment by tebeka** [comment]
IMO this should work out-of-the-box. Will tests once I have working credentials

**Comment by tebeka** [comment]
Tested in the dask tests

**Comment by ashish6912** [comment]
can you share a working example for this in MLrun function with kind = 'dask'?

**Comment by tebeka** [comment]
I don't have an MLRun example, but [test_dask.py](https://github.com/v3io/v3io-fs/blob/master/tests/test_dask.py) has a couple.
